In [71]:
import os
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf

In [3]:
ls

adults_tsl_tbt_famphase.csv*           kids_vsl_tbt_famphase_falsePos.csv*
adults_tsl_tbt_famphase_falsePos.csv*  kids_vsl_tbt_testphase.csv*
adults_tsl_tbt_testphase.csv*          linear_mixed_effects_modeling.ipynb
adults_vsl_tbt_famphase.csv*           old/
adults_vsl_tbt_famphase_falsePos.csv*  plot_all.ipynb
adults_vsl_tbt_testphase.csv*          readme.txt*
kids_tsl_tbt_famphase.csv*             summary.ipynb*
kids_tsl_tbt_famphase_falsePos.csv*    summary_outputs/
kids_tsl_tbt_testphase.csv*            tsl_tbt_kids_allpar_scatter.png
kids_vsl_tbt_famphase.csv*             vsl_tbt_kids_allpar_scatter.png


In [73]:
tsl = pd.read_csv('summary_outputs/summary_kids_tsl.csv', index_col=0)
od = pd.read_csv('summary_outputs/children_all.csv')
tsl.head()
print od.columns.values
skip_kids = od[od['group'] != 'TD'].ID.values
data = tsl[~tsl.id_rt.isin(skip_kids)]

['ID' 'gender' 'group' 'SLAge' 'BehAge' 'AgeInt' 'celf_rs' 'cls' 'kbit'
 'ctopp_e' 'ctopp_bw' 'ctopp_md' 'ctopp_nwr' 'ran_o' 'ran_c' 'ran_l'
 'ran_s' 'trog' 'wrmt_wi' 'wrmt_wa' 'towre_swe' 'towre_rd' 'towre_total'
 'wjiii' 'awma_x' 'awma_b' 'scq' 'srs']


In [74]:
skip_kids = od[od['group'] != 'TD'].ID.values
data = tsl[~tsl.id_rt.isin(skip_kids)]

In [76]:
data_sub = data[['lm_coef_rt','mean_rt','poly1','poly2','poly3','acc']]

<h4>Linear mixed model, slope and intercept as random Checking response time as a function of trial mask</h4>


In [80]:
mod = smf.ols(
    formula = "acc ~ lm_coef_rt",
    data=data_sub
)

res = mod.fit()
print(res.summary())

                            OLS Regression Results                            
Dep. Variable:                    acc   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.030
Method:                 Least Squares   F-statistic:                   0.01476
Date:                Fri, 27 Jan 2017   Prob (F-statistic):              0.904
Time:                        15:27:57   Log-Likelihood:                 22.918
No. Observations:                  35   AIC:                            -41.84
Df Residuals:                      33   BIC:                            -38.72
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
Intercept      0.6484      0.022     29.560      0.0

In [82]:
mod = smf.mixedlm(
    formula = "acc ~ mean_rt", 
    data = data, 
    groups = data['id_rt'],
    missing='drop',
    re_formula = "~mean_rt"
)

mod_fit = mod.fit()
print(mod_fit.summary())

               Mixed Linear Model Regression Results
Model:                  MixedLM     Dependent Variable:     acc    
No. Observations:       35          Method:                 REML   
No. Groups:             35          Scale:                  0.0060 
Min. group size:        1           Likelihood:             16.0384
Max. group size:        1           Converged:              Yes    
Mean group size:        1.0                                        
-------------------------------------------------------------------
                          Coef.  Std.Err.   z   P>|z| [0.025 0.975]
-------------------------------------------------------------------
Intercept                  0.604    0.076 7.909 0.000  0.455  0.754
mean_rt                    0.000    0.001 0.418 0.676 -0.001  0.002
Intercept RE               0.067                                   
Intercept RE x mean_rt RE -0.000                                   
mean_rt RE                 0.000                               

/om/user/ysa/fmri_env/lib/python2.7/site-packages/statsmodels/regression/mixed_linear_model.py:1717: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)


In [38]:
ztd_list = """
3064
3067
3068
3078
3089
3112
3113
3115
3130
3139
3142
3143
3144
3161
3181
3182
3187
3199
3213
3219
3220
3223
3224
3236
3237
3266
3267
3268
3308
3311
3314
3330
3331
3332
3347
""".strip().split('\n')

In [30]:
len(ztd_list)

35

In [29]:
len(td_use)

38

In [23]:
skip_kids

array([3117, 3126, 3206, 3217, 3287, 3288, 3233, 3299, 3300, 3315])

In [43]:
np.setdiff1d(td_use, ztd_list)

array([3123])

In [31]:
skip_kids

array([3117, 3126, 3206, 3217, 3287, 3288, 3233, 3299, 3300, 3315])